MAIN: MOV AL,0A0H
    OUT C6H,AL
    MOV AL,01
    OUT 0C6H,AL
    XOR AX,AX
    MOV DS,AX
    MOV AX,2000H
    MOV WORD PTR [002CH],AX
    MOV AX,1000H
    MOV WORD PTR [002EH],AX
    MOV AL,0DH
    OUT 0C6H,AL
    STI

TINTR: MOV AL,[DI]
    OUT 0C0H,AL
    MOV AL,00
    OUT 0C6H,AL
    INC AL
    OUT 0C6H,AL

    IRET
