MAXLEN = 10
BUFFLEN = MAXLEN + 1
DATA SEGMENT
BUFF1 DB BUFFLEN,0,BUFFLEN DUP(?)
NUM1 EQU BUFF1+2
BUFF2 DB BUFFLEN,0,BUFFLEN DUP(?)
NUM2 EQU BUFF2+2
RESULT DB BUFFLEN DUP(?),24H
DIGITL DB '0123456789'
DIGLEN EQU $-DIGITL
MESS DB 'INVALID NUMBER',0DH,0AH,24H
DATA ENDS
CODE SEGMENT
    ASSUME CS:CODE,DS:DATA,ES:DATA
START: MOV AX,DATA
       MOV DS,AX
       MOV ES,AX
       MOV DX,OFFSET BUFF1
       CALL GETNUM
       JC OVER
       MOV DX,OFFSET BUFF2
       CALL GETNUM
       JC OVER
       MOV SI,OFFSET NUM1
       MOV DI,OFFSET NUM2
       MOV CX,MAXLEN
       CALL ADDITION
       MOV DX,OFFSET RESULT
       CALL DISPNUM
       JMP SHORT OK
OVER:  MOV AX, OFFSET MESS
       MOV AH,9
       INT 21H
OK:    MOV AH,4CH
       INT 21H

GETNUM PROC
    MOV AH,10
    INT 21H
    CALL NEWLINE
    CALL ISDNUM
    JC GETNUM2
    MOV SI,DX
    INC SI
    MOV CL,[SI]
    XOR CH,CH
    MOV AX,MAXLEN
    STD
    MOV DI,SI
    ADD SI,CX
    REP MOVSB
    MOV CX,AX
    JCXZ GETNUM1
    XOR AL,AL
    REP STOSB
GETNUM1: CLD
        CLC
GETNUM2: RET
GETNUM ENDP

ADDITION PROC
    STD
    ADD BX,CX
    ADD SI,CX
    ADD DI,CX
    DEC SI
    DEC DI
    XCHG DI,BX
    INC BX
    CLC
ADDP1: DEC BX
       LODSB
       ADC AL,[BX]
       AAA
       STOSB
       LOOP ADDP1
       MOV AL,0
       ADC AL,0
       STOSB
       CLD
       RET
ADDITION ENDP

DISPNUM PROC
    MOV DI,DX
    MOV AL,0
    MOV CX,MAXLEN
    REPZ SCASB
    DEC DI
    MOV DX,DI
    MOV SI,DI
    INC CX
DISPNU2: LODSB
    ADD AL,30H
    STOSB
    LOOP DISPNU2
    MOV AH,9
    INT 21H
    RET 
DISPNUM ENDP

ISDNUM PROC
    MOV SI,DX
    LODSB
    LODSB
    MOV CL,AL
    XOR CH,CH
    JCXZ ISDNUM2
ISDNUM1: LODSB
    CALL ISDECM
    JNZ ISDNUM2
    LOOP ISDNUM1
    RET
ISDNUM2: STC 
    RET
ISDNUM ENDP

ISDECM PROC
    PUSH CX
    MOV DI,OFFSET DIGITL
    MOV CX,DIGLEN
    REPNE SCASB
    POP CX
    RET
ISDECM ENDP

NEWLINE PROC
    PUSH AX
    PUSH DX
    MOV DL,0DH
    MOV AH,2
    INT 21H
    MOV DL,0AH
    MOV AH,2
    INT 21H
    POP DX
    POP AX
    RET
NEWLINE ENDP
    
CODE ENDS
    END START