;设BUFFER缓冲区有10个单元字节无符号整数，由小到大排序D
DATA SEGMENT
BUFFER DB 23,12,45,67,89,10,34,56,78,90
N EQU 10
DATA ENDS
CODE SEGMENT
    ASSUME CS:CODE,DS:DATA
START: MOV AX,DATA
       MOV DS,AX
       MOV BX,OFFSET BUFFER-1
       MOV SI,1
FORI:  MOV DI,SI
       INC DI
FORJ:  MOV AL,[BX+SI]
       CMP AL,[BX+DI]
       JBE NEXTJ
       XCHG AL,[BX+DI]
       MOV [BX+SI],AL
NEXTJ: INC DI
       CMP DI,N
       JBE FORJ
NEXTI: INC SI
       CMP SI,N-1
       JBE FORI
       MOV AH,4CH
       INT 21H
CODE ENDS
     END START
